name: Apply changes terraform prod

on: 
  push:
    tags:
      - v[12].[0-9]+.[0-9]+

env:
  AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
  AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}

jobs:
  plan-aws:
    name: 'terraform apply aws'
    runs-on: ubuntu-latest
    defaults: 
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v2
    - uses: hashicorp/setup-terraform@v2

    - name: Terraform fmt
      id: fmt
      run: terraform fmt -check
      continue-on-error: true

    - name: Terraform Init
      id: init 
      run: terraform init -backend=true -backend-config="enviroments/aws_prod/backend.hcl"

    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color

    - name: Terraform Apply
      id: apply
      run: terraform apply -auto-aprove -lock=false -var-file="enviroments/aws_prod/terraform.tfvars"