name: Create terraform plan

on: 
  pull_request:

env:
  AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
  AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}

jobs:
  plan-aws:
    name: 'terraform plan aws'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        path:
          - hs-event-scheduler
          - hs-traffic-events

    defaults: 
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v2
    - uses: hashicorp/setup-terraform@v2

    - name: Terraform fmt
      id: fmt
      run: terraform fmt -check
      continue-on-error: true

    - name: Terraform Init
      id: init 
      working-directory: ${{ matrix.path }}
      run: 
        terraform init -backend=true -backend-config="../enviroments/aws/backend.hcl"

    - name: Terraform Validate
      id: validate
      working-directory: ${{ matrix.path }}
      run: 
        terraform validate -no-color

    - name: Terraform Plan
      id: plan
      working-directory: ${{ matrix.path }}
      run: 
        terraform plan -no-color -lock=false -var-file="../enviroments/aws/terraform.tfvars"
      continue-on-error: true

    - name: Post Plan to GitHub PR
      uses: mshick/add-pr-comment@v1
      with:
        allow-repeats: true
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        repo-token-user-login: 'github-actions[bot]'
        message: |
          ## ${{ matrix.path }} plan
          ```
          ${{ steps.plan.outputs.stdout || steps.plan.outputs.stderr }}
          ```  
    
    

  